#!/usr/bin/env ruby
require 'rubygems'
require 'activesupport'

STDOUT.sync = true
Time::DATE_FORMATS[:timecode] = "%H:%M:%S.00"

Signal.trap("HUP") do
  exit
end

Signal.trap("INT") do
  puts "Capture Stopped"
  exit
end

puts "Found AV/C device with GUID 0x006037004e545301"
puts "Capture Started"

size, frames, timecode = 0, 0, Time.now.at_beginning_of_day

loop do
  puts %Q["dvgrab-001.dv": #{size.to_s.rjust(5)}.00 MiB #{frames.to_s.rjust(5)} frames timecode #{timecode.to_s(:timecode)} date #{Time.now.to_s(:db)}]
  timecode += 1.second
  frames += 25
  size += 1
  sleep 0.1
end
