#!/usr/bin/env ruby
require 'rubygems'
require 'activesupport'

# dvgrab -showstatus -noavc -f dv1 /home/equipe/eqpvideo
output_file = ARGV.pop || "dvgrab-001"

STDOUT.sync = true
Time::DATE_FORMATS[:timecode] = "%H:%M:%S.00"

Signal.trap("HUP") do
  exit
end

Signal.trap("INT") do
  STDOUT.puts "Capture Stopped"
  exit
end

STDOUT.puts "Found AV/C device with GUID 0x006037004e545301"
STDOUT.puts "Capture Started"

size, frames, timecode = 0, 0, Time.now.at_beginning_of_day

loop do
  STDOUT.puts %Q["#{output_file}.avi": #{size.to_s.rjust(5)}.00 MiB #{frames.to_s.rjust(5)} frames timecode #{timecode.to_s(:timecode)} date #{Time.now.to_s(:db)}\r]
  timecode += 1.second
  frames += 25
  size += 1
  sleep 0.1
end
